username = input("Username: ")
age = int(input("Age: "))
reports = int(input("Number of reports: "))
warning = int(input("Number of warnings: "))
bans = int(input("Number of bans: "))

risk_score = (reports * 2) + (warning * 5) + (bans * 10)
print(f"User: {username}")
print(f"Age: {age}")
print(f"Reports: {reports}")
print(f"Number of Warnings: {warning}")
print(f"Bans: {bans}")
print(f"Risk Score: {risk_score}")